@startuml
allowmixing
title Tree Edit

'
' Schema
'
entity tree {
  * id: integer <<PK>>
  --
  * parent: integer
  * row: integer
  * data: text
}

' sqlite3 sample.db
' create table tree (id integer primary key autoincrement, parent integer, row integer, data text);
' create index if not exists idx_tree_parent on tree (parent);
' .quit
@enduml
