name: pages
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/pages.yml
      - pages/**

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install Python Requirements
        run: |
          pip install -r requirements.txt
      - name: Build MkDocs
        run: |
          cd pages
          mkdocs build
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages/site
  deploy:
    environment:
      name: pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-latest
    needs: build
    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
